name: Android Build APK

on:
  push:
    branches: [ "main" ] # Cambia a "master" si ese es el nombre de tu rama principal
  workflow_dispatch: # Esto permite ejecutar el proceso manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Dar permisos de ejecución a Gradle
        run: chmod +x gradlew

      - name: Compilar APK de Debug
        run: ./gradlew assembleDebug

      - name: Subir el APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
